#!/bin/sh
#
# UniFi Protect Docker Init
# Copyright (C) 2019 James T. Lee
#
# Starts the unifi-protect service and its database
#

pg_ctlcluster 10 main start
su postgres -c 'createuser unifi-protect -d'
unifi-protect 2>&1 | grep -v '^Unknown QEMU_IFLA_INFO_KIND'
pg_ctlcluster 10 main stop
